### ISSUE TITLE
Problems with this extension

### ISSUE THREAD

**Issue by Xlmlkk** [worksasintended/klipper_linear_movement_analysis#15]
After entering the command with parameters, it produces this:
{'error': 'WebRequestError', 'message': "'<' not supported between instances of 'NoneType' and 'int'"}

I run on: OrangePI 3 Lts

When entering a command without parameters, images with data are created.

**Comment by worksasintended** [comment]
Can you give me the full command you are using?

**Comment by worksasintended** [comment]
Oh, I think I know what happened:
Those brackets are part of what is called "Backus-Naur-form". They indicate parameters to set, and should not be put in with the command.

**Comment by Xlmlkk** [comment]
It looks like I'm doing something wrong, but I don't understand what

![image](https://github.com/worksasintended/klipper_linear_movement_analysis/assets/115371514/c8e9daf3-26b3-4386-be8b-0fb9628c7dc6)


$ MEASURE_LINEAR_VIBRATIONS_RANGE AXIS=xy STARTX=10 STARTY=10 ENDX=240 ENDY=10 VMIN=40 VMAX=100 STEP=10
![image](https://github.com/worksasintended/klipper_linear_movement_analysis/assets/115371514/df35ed1a-c617-4344-a690-f00f17d71646)

**Comment by worksasintended** [comment]
There is no Axis xy, its either x, or y, or a or b and with xy you managed to bypass my test for valid input. This will be fixed.

**Comment by Xlmlkk** [comment]
Add a couple of real examples of using commands (I'm not the only one who doesn't immediately understand how to write a command)

The problem has not disappeared, on all axes it gives out this. The size for x and y was different, always the same
![image](https://github.com/worksasintended/klipper_linear_movement_analysis/assets/115371514/20d57cba-55fe-4ad4-9616-6958d2365d4a)

how to make a graph of the whole table, not just one line?

**Comment by worksasintended** [comment]
Looks like you are either sitting on an old installation of klipper (which is not python3) or you dont use the latest version of this package (which is required since klipper moved to py3)

**Comment by Xlmlkk** [comment]
klipper is installed on py3. Try to update py3

**Comment by worksasintended** [comment]
just use moonraker to update to version 1.0 of this package then.
