### ISSUE TITLE
Invalid adxl345 id (got 0 vs e5).

### ISSUE THREAD

**Issue by stenmic** [worksasintended/klipper_linear_movement_analysis#16]
After starting "MEASURE_LINEAR_VIBRATIONS_RANGE AXIS=x VMIN=50 VMAX=100 STEP=5" I immediately get this error message.

-------------------------------------------------- ------------------------------------------------------
Invalid adxl345 id (got 0 vs e5).
This is generally indicative of connection problems
(e.g. faulty wiring) or a faulty adxl345 chip.
-------------------------------------------------- ------------------------------------------------------

Input Shaper works without any problems.

My Printer.cfg:

[adxl345 X]
cs_pin: EBB: PB12
spi_software_sclk_pin: EBB: PB10
spi_software_mosi_pin: EBB: PB11
spi_software_miso_pin: EBB: PB2
axes_map: x,y,z

[adxl345 Y]
cs_pin: PI4:None

[resonance_tester]
accel_chip_x: adxl345 X
accel_chip_y: adxl345 Y
probe_points:
    125, 130, 30

[linear_movement_vibrations]
#accel_chip: adxl345
accel_chip_x: adxl345 X
accel_chip_y: adxl345 Y
x_min: 20
x_max: 230
y_min: 20
y_max: 245
output_directory: /home/pi/printer_data/config/linear_vibrations/

**Comment by rgrgrg** [comment]
Klipper on rp2040 has problem with correct SPI initialization. My workaround:
```
[gcode_macro ADXL_INIT]
description: PICO has problems with ADXL initialization
gcode:
        ACCELEROMETER_DEBUG_READ REG=0 CHIP=X
        ACCELEROMETER_DEBUG_READ REG=0 CHIP=Y

[delayed_gcode ADXL_DELAYED]
initial_duration: 1
gcode:
        ADXL_INIT
```

**Comment by worksasintended** [comment]
As this is unrelated to this specific package I will close this issue. Feel free to reopen if necesarry.
